config/routes.rb
SampleApp::Application.routes.draw do

  resources :microposts do
    resources :post_comments
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy, :show]
  resources :baners,    only: [:show]
  resources :relationships, only: [:create, :destroy]
  root to: 'static_pages#index'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/home', to: 'static_pages#home', via: 'get'
  match '/news', to: 'news_posts#index', via: 'get'
  resources :categories, only: [:show]
  resources :news_posts, only: [:show]
  resources :post_comments, only: [:show]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :microposts
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.where(:id => params[:id]).first
    category_id = @category.id
    @posts = Micropost.where(category_id: category_id)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_categories.html.erb
<div class="categories">
  <ul>
    <% Category.all.each do |category| %>
        <li><%= link_to category.name, category_path(category.id) %></li>
    <% end %>
  </ul>
</div>

app/views/categories/show.html.erb
<div class="col-md-8">
<% @posts.each do |post| %>
    <div class="blog-post">
      <div class="blog-image">
        <%= image_tag post.picture.url if post.picture? %>

      </div>
      <div class="blog-details">
        <p>
          <i class="glyphicon glyphicon-calendar"></i><%= post.created_at %>,
          <i class="glyphicon glyphicon-user"></i><%= post.user.name %>
        </p>
      </div>
      <div class="blog-content">
        <h3 class="blog-head"><%= post.category.name %></h3>
        <p><%= post.content%> </p>
      </div>
    </div>

<% end %>
</div>
<div class="col-md-4">
<%= render 'categories/categories'%>
    </div>